### ISSUE TITLE
Jeffail/gabs changed function methods

### ISSUE THREAD

**Issue by andysnowden** [jefferai/jsonx#1]
The gabs library changed the function return for `Children()` and `ChildrenMap()` as of version 2.0.0

`# github.com/EquityZen/go/vendor/github.com/jefferai/jsonx
../../vendor/github.com/jefferai/jsonx/jsonx.go:88:22: assignment mismatch: 2 variables but 1 values
../../vendor/github.com/jefferai/jsonx/jsonx.go:115:22: assignment mismatch: 2 variables but 1 values`

**Comment by jefferai** [comment]
Fixed in v1.0.1, thanks for the report.
